### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by sydios** [imperian/MMM-TAF#5]
Hello,

since a couple of days the module doesn't work anymore. It worked for a long time, but now MM wouldn't start when it's active. 
Here is the log:

App threw an error during load
0|MagicMirror  | [16.07.2022 21:38.59.734] [ERROR]
0|MagicMirror  | Error: Cannot find module 'request'
0|MagicMirror  | Require stack:
0|MagicMirror  | - /home/pi/MagicMirror/modules/MMM-TAF/node_helper.js
0|MagicMirror  | - /home/pi/MagicMirror/js/app.js
0|MagicMirror  | - /home/pi/MagicMirror/js/electron.js
0|MagicMirror  | - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
0|MagicMirror  | -
0|MagicMirror  |     at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
0|MagicMirror  |     at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
0|MagicMirror  |     at Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
0|MagicMirror  |     at Module._load (node:internal/modules/cjs/loader:785:27)
0|MagicMirror  |     at c._load (node:electron/js2c/asar_bundle:5:13343)
0|MagicMirror  |     at Module.require (node:internal/modules/cjs/loader:1012:19)
0|MagicMirror  |     at require (node:internal/modules/cjs/helpers:102:18)
0|MagicMirror  |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-TAF/node_helper.js:12:15)
0|MagicMirror  |     at Module._compile (node:internal/modules/cjs/loader:1118:14)
0|MagicMirror  |     at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
0|MagicMirror  | [16.07.2022 21:38.59.737] [ERROR] Whoops! There was an uncaught exception...
0|MagicMirror  | [16.07.2022 21:38.59.754] [ERROR]
0|MagicMirror  | Error: Cannot find module 'request'
0|MagicMirror  | Require stack:
0|MagicMirror  | - /home/pi/MagicMirror/modules/MMM-TAF/node_helper.js
0|MagicMirror  | - /home/pi/MagicMirror/js/app.js
0|MagicMirror  | - /home/pi/MagicMirror/js/electron.js
0|MagicMirror  | - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
0|MagicMirror  | -
0|MagicMirror  |     at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
0|MagicMirror  |     at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
0|MagicMirror  |     at Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
0|MagicMirror  |     at Module._load (node:internal/modules/cjs/loader:785:27)
0|MagicMirror  |     at c._load (node:electron/js2c/asar_bundle:5:13343)
0|MagicMirror  |     at Module.require (node:internal/modules/cjs/loader:1012:19)
0|MagicMirror  |     at require (node:internal/modules/cjs/helpers:102:18)
0|MagicMirror  |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-TAF/node_helper.js:12:15)
0|MagicMirror  |     at Module._compile (node:internal/modules/cjs/loader:1118:14)
0|MagicMirror  |     at Module._extensions..js (node:internal/modules/cjs/loader:1173:10) {
0|MagicMirror  |   code: 'MODULE_NOT_FOUND',
0|MagicMirror  |   requireStack: [
0|MagicMirror  |     '/home/pi/MagicMirror/modules/MMM-TAF/node_helper.js',
0|MagicMirror  |     '/home/pi/MagicMirror/js/app.js',
0|MagicMirror  |     '/home/pi/MagicMirror/js/electron.js',
0|MagicMirror  |     '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
0|MagicMirror  |     undefined
0|MagicMirror  |   ]

**Comment by imperian** [comment]
Request was installed originally with the MMM bundle.  I wonder if they removed the dependency.  Try this: go to your MMM main directory and do `npm install request`.  If they removed that dependency then that should put it back on yours.  If it does then I'll need to include it in the module itself or use whatever MMM switched to.

**Comment by JHammer494** [comment]
Hey! Ive had the same issue, and it seems that Request has been permanently Deprecated. 

> https://www.npmjs.com/package/request

But i am in work to refactor to use Axios as a lightweight replacement to get and display data!

**Comment by imperian** [comment]
I've updated the code to remove the request dependency and switched to ky.  See how that works
